PREFIX dataset1210: <http://logd.tw.rpi.edu/source/data-gov/dataset/1210/vocab/raw/>
SELECT  ?state (COUNT(?state) as ?stateCount) (SUM(xsd:int(?emergency_beds)) as ?emergency_beds) (SUM(xsd:int(?icu)) as ?ICU) 
WHERE { 
  graph ?g{
        ?s dataset1210:state ?state.
  	?s dataset1210:emergency_room_beds ?emergency_beds .
        ?s dataset1210:intensive_care_unit_class ?icu .
		FILTER((?state != "PR") && (?state != "DC"))
  }
} 
order by ?state